import type { Metadata } from "next";
import NavContextProvider from "@/context/Navcontext";
import OptionContextProvider from "@/context/OptionContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Student Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
      </head>
      <body className="font-poppins overflow-hidden">
        <OptionContextProvider>
          <NavContextProvider>
            <>{children}</>
          </NavContextProvider>
        </OptionContextProvider>
      </body>
    </html>
  );
}
