import type { Metadata } from "next";
import NavContextProvider from "@/context/Navcontext";
import OptionContextProvider from "@/context/OptionContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Student Dashboard | GIAIC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.1/css/all.min.css"
          integrity="sha512-5Hs3dF2AEPkpNAR7UiOHba+lRSJNeM2ECkwxUIxC1Q/FLycGTbNapWXB4tP889k5T5Ju8fs4b1P5z/iB4nMfSQ=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body>
        <OptionContextProvider>
          <NavContextProvider>
            <>{children}</>
          </NavContextProvider>
        </OptionContextProvider>
      </body>
    </html>
  );
}
